// <auto-generated />
using EfCoreDeleting_Related_Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreDeletingRelatedData.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20221117132043_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("EfCoreDeleting_Related_Data.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Yiyecek"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "icecek"
                        });
                });

            modelBuilder.Entity("EfCoreDeleting_Related_Data.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriId = 1,
                            UrunAdi = "Peynir"
                        },
                        new
                        {
                            Id = 2,
                            KategoriId = 1,
                            UrunAdi = "Ekmak"
                        },
                        new
                        {
                            Id = 3,
                            KategoriId = 1,
                            UrunAdi = "Kavun"
                        },
                        new
                        {
                            Id = 4,
                            KategoriId = 1,
                            UrunAdi = "Karpuz"
                        });
                });

            modelBuilder.Entity("EfCoreDeleting_Related_Data.Urun", b =>
                {
                    b.HasOne("EfCoreDeleting_Related_Data.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("EfCoreDeleting_Related_Data.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
